name = "Newb X Mashi v15.11"
version = [0, 15, 11]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- Note : Some bug(s) may still haven't fixed yet
%v
§3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["mashind", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "9dc15800-8161-4d8d-99df-c8911deba36c" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "EndSky", "Clouds", "SunMoon", "Weather", "Stars", "ActorGlint"]

[info] 
copyright = '''
Copyright © 2024 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
Credit the EndSky by @jcgaming7125_17548 (discord)
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk", "Clouds"]
description = '''
No fog and wave effects, No cloud layers
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Clouds color match with sky
'''

[[subpack]]
define = "BETTER_CLOUD_AND_SIMPLES"
materials = ["Clouds"]
description = '''
Better cloud color, no glowing flowers, no clouds layers
'''

[[subpack]]
define = "BETTER_CLOUD"
materials = ["Clouds"]
description = '''
Better cloud color
'''
