name = "Newb X Mashi v15.12"
version = [0, 15, 12]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- Note : Some bug(s) may still haven't fixed yet

Recommend Minecraft Settings
- 0 Brightness
- 8 RenderChunk
- 70 FOV

%v
§3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["mashind", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "9dc15800-8161-4d8d-99df-c8911deba36c" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "EndSky", "Clouds", "SunMoon", "Weather", "Stars", "Actor", "ItemInHandColor", "ItemInHandTextured"]

[info] 
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
Credit the EndSky by @jcgaming7125_17548 (discord)
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "NO_WAVE_FOG_1"
materials = ["RenderChunk", "Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
No fog and wave effects, 1 Layer Clouds
'''

[[subpack]]
define = "NO_WAVE_FOG_2"
materials = ["RenderChunk", "Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
No fog and wave effects, 2 Layers Clouds
'''

[[subpack]]
define = "NO_WAVE_FOG_3"
materials = ["RenderChunk", "Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
No fog and wave effects, 3 Layers Clouds
'''

[[subpack]]
define = "DEFAULT_1"
materials = ["Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
Clouds Color Match With Sky Color, 1 Layer Clouds
'''

[[subpack]]
define = "DEFAULT_2"
materials = ["Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
Clouds Color Match With Sky Color, 2 Layers Clouds
'''

[[subpack]]
define = "DEFAULT_3"
materials = ["Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
Clouds Color Match With Sky Color, 3 Layers Clouds
'''

[[subpack]]
define = "SIMPLES"
materials = ["Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
No Glowing Flowers, No Fake Fireflies Leaves, 1 Clouds Layer
'''


[[subpack]]
define = "LAYER_CLOUD_1"
materials = ["Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
1 Layer Clouds
'''

[[subpack]]
define = "LAYER_CLOUD_2"
materials = ["Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
2 Layers Clouds
'''

[[subpack]]
define = "LAYER_CLOUD_3"
materials = ["Clouds", "ActorGlint", "ItemInHandColorGlint"]
description = '''
3 Layers Clouds
'''